name: main
on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Make Build
        run: make build
      - name: Make Test
        run: make test
      - name: Publish Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.CICD_GITHUB_TOKEN }}
          publish_dir: ./dist
